### ISSUE TITLE
Unistalled Aya but open with Aya didn't disappear

### ISSUE THREAD

**Issue by HyperTNTClown** [7room/aya#1]
Hello I unistalled Aya because my Trial was over, but the open with Aya shortcut didn't disappear. How do I delete it?

**Comment by nomba** [comment]
Hi @HyperTNTClown! Thank you for your request. Actually we are working on a new release `0.11.0` and this problem will be fixed. To solve it now you can remove two registry key **manually**:
```
HKEY_CLASSES_ROOT\Drive\shell\Aya
HKEY_CLASSES_ROOT\Directory\Background\shell\Aya
```
You can use Registry Editor (*regedit.exe*)
or just **run the following commands** via Command Prompt (*cmd.exe*) with administrator privileges

```bat
REG DELETE HKEY_CLASSES_ROOT\Drive\shell\Aya
REG DELETE HKEY_CLASSES_ROOT\Directory\Background\shell\Aya
```
