### ISSUE TITLE
How to silent install 7room aya without it launching after install

### ISSUE THREAD

**Issue by jgstew** [7room/aya#2]
After silent install of aya it is launching. This causes problems with completion. 

Is there an InnoSetup task that can be disabled to prevent this? Right now getaya.co isn't loading and I don't see any documentation on silent install commands.

**Comment by paulem** [comment]
Hi! Indeed, in 0.10.4 it is not possible to perform a silent installation without starting the application at the end of the setup.
But now you can do this using [0.10.5](https://github.com/7room/aya/releases/tag/v0.10.5) with the `/norun` parameter, i.e. `Aya.Setup.0.10.5.exe /silent /norun` or `Aya.Setup.0.10.5.exe /verysilent /norun` .

But, I want to warn you that unfortunately version `0.10.5` is not digitally signed and is unlikely to be signed anytime soon. I'm sorry if this may be a problem for you.
