### ISSUE TITLE
No way to upgrade anymore?

### ISSUE THREAD

**Issue by driftywinds** [7room/aya#3]
**Versions**
 - Aya version: 0.10.15
 - OS: Windows 11

Clicking on upgrade now takes me to the winget.pro site and I can't buy a license. Is there no way to support Aya anymore?

**Comment by paulem** [comment]
Hi. Thank you for your interest in supporting the project! However, I need to let you know that the project is currently frozen. If you still want to get the advanced version, I can try to generate a license for you for free or come up with something else for you to get the upgrade. To do so, email aya@7room.net.

**Comment by driftywinds** [comment]
Alright I'll send you an email!
